# Generated by Django 4.2.4 on 2023-08-06 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Movie Name')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['name'],
            },
        ),
    ]
