# Generated by Django 4.2.4 on 2023-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
